server:
  port: 8443
  ssl:
    key-store: classpath:mykeys.jks
    key-store-password: letmein
    key-password: letmein

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root
    password: hjh2019$
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    tacos: DEBUG
    root: INFO

greeting:
  welcome: You are useing ${spring.application.name}.

taco:
  orders:
    pageSize: 10
